const reactProjects = {
  wildOasis: {
    imgSrc: "./wildOasis.png",
    imgAlt: "project",
    title: "Wild Oasis (Hotel management system)",
    briefIntro:
      "hotel management system (employees interface only) for cabins in the wild instead of buildings in the towns",
    details: [
      "Accounts system and real authentication with ability to create new users",
      "full control of adding cabins, guests, bookings and edit all settings (CRUD)",
      "Clean code, taking care about performance, powerful design patterns and efficient file structure",
      "Big and complex global & remote state management",
      "Efficient way of dealing with lack of resources such as (deleting the old images after uploading the new one. Supabase doesn't have like this function in storage)",
      "Used the lazy loading components according to the the big amount of pages",
      "Lazy loading images for more user-experience",
      "A lot of reusable custom hooks and components",
      "Powerful and multiple charts for dashboard with Rechart",
      "Ability to search in realtime for guests (Race condition solved)",
      "Dark mode with best practices",
      "Pagination for guests and booking",
      "Used both service side filter with sorting and client side for more user-experience",
      "Used the most user-friendly effects like fading, collapsing and more. builded from scratch (DOM manipulation)",
    ],
    warnings: [
      "This app use real accounts and only employees can add one so please use this one to give the app a shot",
      "Email: magolon226@hisotyr.com,Password: lili123#",
      "Dashboard statistics may show nothing so feel free to add guests and bookings (there is existing guests and you can just add bookings)",
    ],
    tools: [
      "React.js",
      "Tanstack-React query",
      "Styled-componenet for CSS",
      "React Router DOM ",
      "Supabase service (backend & database)",
    ],
    projectUrl: "https://osama78assi.github.io/WildOasis/",
    codeUrl: "https://github.com/osama78assi/WildOasis",
  },
  fastPizza: {
    imgSrc: "./fastPizza.png",
    imgAlt: "project",
    title: "fast pizza",
    briefIntro: "in this app you can order as many as you want from pizza",
    details: [
      "the new React Router feature of routing",
      "render as you fetch approach",
      "fetching data from another page without navigating to it",
      "cart feature using the power of Redux toolkit",
      "managing some pieces of remote state using middlewares and async thunk",
      "styling using one of the powerful CSS framework Tailwind CSS",
    ],
    warnings: [],
    tools: [
      "React.js",
      "Redux Toolkit",
      "Tailwind CSS",
      "React Router DOM v6.22.0",
    ],
    projectUrl: "https://osama78assi.github.io/fastPizza/",
    codeUrl: "https://github.com/osama78assi/fastPizza",
  },
  worldWise: {
    imgSrc: "./worldWise.png",
    imgAlt: "project",
    title: "world wise",
    briefIntro:
      "in this app you can keep track of any journey you have traveld throw your life",
    details: [
      "protecting some pages in the app if the user not logged in",
      "custom hook for managing the session storage to know if the user logged in or not",
      "lazy loading components feature in react with suspense component",
      "context API to manage global state with best practices",
      "handling complex routing using the classic way of React Router",
      "handeling events on the map with React Leaflet library ",
      "time limit for some api requests for more user friendly interface",
      "styling the components using CSS modules instead of global classes",
    ],
    warnings: [
      "this app using fake authentication just use the prefilled input data",
    ],
    tools: ["React", "React Router DOM", "React Leaflet"],
    projectUrl: "https://osama78assi.github.io/worldWise/",
    codeUrl: "https://github.com/osama78assi/worldWise",
  },
  toDo: {
    imgSrc: "./toDoApp.png",
    imgAlt: "project",
    title: "todo application",
    briefIntro: "you can schedule your daily tasks using groups feature",
    details: [
      "the classic way of routing in React Router DOM",
      "many DOM manipulation operations using Ref like collapse effect, custom slider",
      "simple dashboard contain all CRUD operations each single task and group",
      "many colors theme available for user and dark mode feature",
      "handling very complex global state using the Redux toolkit",
      "almost every action is middleware because using custom hook for local storage",
      "very flexible app and reusable styling using SCSS",
    ],
    warnings: [],
    tools: ["React", "React Router DOM", "Redux Toolkit", "SCSS"],
    projectUrl: "https://osama78assi.github.io/todoApp/",
    codeUrl: "https://github.com/osama78assi/todoApp",
  },
  movies: {
    imgSrc: "./movies.png",
    imgAlt: "project",
    title: "Movies App",
    briefIntro: "you can search about almost any film using IMDB API",
    details: [
      "search feature with API request",
      "handling some problems that may user face in his internet connection",
      "handling race condition problem by aborting the current request and send the new one",
    ],
    warnings: [],
    tools: ["React", "CSS"],
    projectUrl: "https://osama78assi.github.io/moviesApp/",
    codeUrl: "https://github.com/osama78assi/moviesApp",
  },
  quiz: {
    imgSrc: "./quiz.png",
    imgAlt: "project",
    title: "Quiz App",
    briefIntro: "simple React quiz app",
    details: ["managing complex state using the power of useReducer hook"],
    warnings: [],
    tools: ["React", "CSS"],
    projectUrl: "https://osama78assi.github.io/quiz/",
    codeUrl: "https://github.com/osama78assi/quiz",
  },
  weather: {
    imgSrc: "./weather.png",
    imgAlt: "project",
    title: "Weatehr App",
    briefIntro:
      "simple weather app where you can search about any country or using your country as default",
    details: [
      "classic weather app using the classic way of react, which is class component",
    ],
    warnings: [],
    tools: ["React(Class component)", "CSS"],
    projectUrl: "https://osama78assi.github.io/weatherApp/",
    codeUrl: "https://github.com/osama78assi/weatherApp",
  },
};

const javaScriptProjects = {
  forkify: {
    imgSrc: "./forkify.png",
    imgAlt: "project",
    title: "Forkify App",
    briefIntro: "here you can search over 10.000 recipes, save your recipes",
    details: [
      "built this app in modern JavaScript with ES6 features",
      "built with MVC architecture",
      "clean code that fulfil most of SOLID principles",
      "time limit for each API request & errors handling",
      "advanced DOM manipulation and async operations. Real time application",
      "search feature with forkify API",
      "form validation with regular expressions",
      "mixed programming paradigms between OOP and FP",
    ],
    warnings: [],
    tools: ["Pure JavaScript", "SCSS"],
    projectUrl: "https://osama78assi.github.io/forkifyApp/",
    codeUrl: "https://github.com/osama78assi/forkifyApp",
  },
  kasper: {
    imgSrc: "./kasper.png",
    imgAlt: "project",
    title: "Kasper",
    briefIntro: "one page templete",
    details: ["DOM manipulation", "styled with pure CSS"],
    warnings: [],
    tools: ["Pure JavaScript", "CSS"],
    projectUrl: "https://osama78assi.github.io/kasper/",
    codeUrl: "https://github.com/osama78assi/kasper",
  },
  bankistDOM: {
    imgSrc: "./bankistDOM.png",
    imgAlt: "project",
    title: "Bankist Application",
    briefIntro: "normal one page template",
    details: [
      "DOM manipulation",
      "tab component",
      "slider component",
      "lazy loading images",
    ],
    warnings: [],
    tools: ["Pure JavaScript", "CSS"],
    projectUrl: "https://osama78assi.github.io/bankistAdvanceDOM/",
    codeUrl: "https://github.com/osama78assi/bankistAdvanceDOM",
  },
  mapty: {
    imgSrc: "./mapty.png",
    imgAlt: "project",
    title: "Mapty Application",
    briefIntro: "here you can plan to your next journey using the map",
    details: [
      "geolocation API",
      "built with Leaflet",
      "used local storage to store",
    ],
    warnings: [],
    tools: ["JavaScript", "Leaflet", "CSS"],
    projectUrl: "https://osama78assi.github.io/mapty/",
    codeUrl: "https://github.com/osama78assi/mapty",
  },
  bankistDashboard: {
    imgSrc: "./bankistDashboard.png",
    imgAlt: "project",
    title: "Bankist Dashboard",
    briefIntro: "simple dashboard for fake bank interface",
    details: ["all CRUD operations", "sort functionality"],
    warnings: [
      "Use This Data: {js, 1111} Or {jd, 2222} Or {st, 3333} Or {ss, 4444}",
    ],
    tools: ["Pure JavaScript", "CSS"],
    projectUrl: "https://osama78assi.github.io/bankistDashboard/",
    codeUrl: "https://github.com/osama78assi/bankistDashboard",
  },
};

const cssProjects = {
  coders: {
    imgSrc: "./coders.png",
    imgAlt: "project",
    title: "Coders Arena",
    briefIntro: "noraml web page",
    details: ["grid and flex property"],
    warnings: [],
    tools: ["CSS"],
    projectUrl: "https://osama78assi.github.io/Coders-Arena/",
    codeUrl: "https://github.com/osama78assi/Coders-Arena",
  },
  bondi: {
    imgSrc: "./bondi.png",
    imgAlt: "project",
    title: "Bondi",
    briefIntro: "simple web page",
    details: ["built with bootstrap"],
    warnings: [],
    tools: ["CSS", "Bootstrap"],
    projectUrl: "https://osama78assi.github.io/Bondi/",
    codeUrl: "https://github.com/osama78assi/Bondi",
  },
  music: {
    imgSrc: "./music.png",
    imgAlt: "project",
    title: "Music Dashboard",
    briefIntro: "styling fake music dashboard",
    details: ["styling responsive complex dashboard with Bootstrap"],
    warnings: [],
    tools: ["CSS", "Bootstrap"],
    projectUrl: "https://osama78assi.github.io/music/",
    codeUrl: "https://github.com/osama78assi/music",
  },
  leon: {
    imgSrc: "./leon.png",
    imgAlt: "project",
    title: "Leon",
    briefIntro: "simple web page",
    details: ["styling with pure CSS"],
    warnings: [],
    tools: ["CSS"],
    projectUrl: "https://osama78assi.github.io/leon/",
    codeUrl: "https://github.com/osama78assi/leon",
  },
};

export { cssProjects, javaScriptProjects, reactProjects };
